import { ReactElement, useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import DefaultLayout from "@/src/layouts/DefaultLayout/DefaultLayout";
import { NavCollections, PackGroup, Banner } from "@/src/components";

function Pack() {
  const router = useRouter();
  const path = router.asPath;
  const paths = [
    "/collections/single-packs",
    "/collections/mixed-packs",
    "/collections/occasions",
    "/collections/merch",
  ];
  const collections = ["Single Packs", "Mixed Packs", "Occasions", "Merch"];
  const [pack, setPack] = useState(null);
  const getCollection = (path: string) => {
    let index = paths.indexOf(path);
    return collections[index];
  };
  const getItems = (path: string) => {
    fetch("/api/collections")
      .then((response) => response.json())
      .then((data) => {
        let filterData = data.filter((a) => a.name === getCollection(path));
        setPack(filterData[0]);
      })
      .catch((error) => {
        console.error("Error:", error);
      });
    return 0;
  };
  useEffect(() => {
    getItems(path);
  }, [path]);
  return (
    pack && (
      <>
        <Head>
          <title>{getCollection(path)} - MOTH</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavCollections />
        <main>
          <PackGroup data={pack} lineBottom={false} />
        </main>
        <Banner />
      </>
    )
  );
}

Pack.getLayout = function getLayout(Pack: ReactElement) {
  return <DefaultLayout>{Pack}</DefaultLayout>;
};

export default Pack;
