import Head from "next/head";
import { ReactElement, useEffect, useState } from "react";
import DefaultLayout from "@/src/layouts/DefaultLayout/DefaultLayout";
import { NavCollections, PackGroup, SinglePacksBanner } from "@/src/components";
import styles from "./gifts.module.css";
import Image from "next/image";
import { gift, truck, mail } from "@/src/assets/icons";

const Gifts = () => {
  const [pack, setPath] = useState(null);
  const getItem = () => {
    fetch("/api/collections")
      .then((response) => response.json())
      .then((data) => {
        data = data.filter((a) => a.name === "Gifts");
        setPath(data[0]);
      })
      .catch((error) => console.error("Error:", error));
  };
  useEffect(() => {
    getItem();
  }, []);
  return (
    <>
      <Head>
        <title>Gifts - MOTH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavCollections />
      <main>
        <div className={styles.banner}>
          <div className={styles.banner_content}>
            <h1>GIFT MOTH</h1>
            <p>
              The perfect present for cocktail lovers. Bring a smile to your
              mate. Or fizz to the family. We’ve put together some perfect
              bundles to gift with ease.
            </p>
          </div>
        </div>
        <div className={`${styles.gifting_container} border-bottom`}>
          <div className={styles.gifting_title}>
            <h1>MOTH</h1>
            <h1>GIFTING</h1>
          </div>
          <div className={styles.gifting_content}>
            <div className={styles.gifting_item}>
              <Image src={truck} alt="icon" />
              <h3>DELIVERED NEXT DAY</h3>
              <p>
                Get it tomorrow - in the nick of time? We can deliver next
                working day when you order before 2pm.
              </p>
            </div>
            <div className={styles.gifting_item}>
              <Image src={gift} alt="icon" />
              <h3>GIFT PACKED</h3>
              <p>
                Simple, elegant packaging, to give your gift an extra touch of
                style.
              </p>
            </div>
            <div className={styles.gifting_item}>
              <Image src={mail} alt="icon" />
              <h3>DELIVERED NEXT DAY</h3>
              <p>
                Get it tomorrow - in the nick of time? We can deliver next
                working day when you order before 2pm.
              </p>
            </div>
          </div>
        </div>
        {pack && <PackGroup data={pack} lineBottom={false} />}
        <SinglePacksBanner />
      </main>
    </>
  );
};

Gifts.getLayout = function getLayout(Gifts: ReactElement) {
  return <DefaultLayout>{Gifts}</DefaultLayout>;
};

export default Gifts;
